Set WindowBar Colorful
Set Theme "Catppuccin Frappe"
Set Framerate 60
Set Shell zsh
Sleep 1s
Type "poetry shell"
Enter
Sleep 1s
Type "python"
Enter
Sleep 1s
Type 'input = "!-/*5[];"'
Sleep 500ms
Enter
Sleep 1s
Type "from interpret_deez import lexer"
Enter
Sleep 1s
Type "lex = lexer.Lexer(input)"
Enter
Sleep 1s
Type "for _ in range(9):"
Sleep 500ms
Enter
Sleep 1s
Type "    lex.next_token()"
Sleep 500ms
Enter 2
Sleep 5s
Ctrl+Z
Type "exit"
Enter
